---
- name: Initial jboss configuration to remote hosts
  hosts: all
  become: true
  tasks:
   - name: Install java and some basic dependencies on rhel7.9
     ansible.builtin.yum:
      name: "{{ packages }}"
     vars:
      packages:
      - unzip
      - java

   - name: Download JBoss from redhat.com
     get_url:
      url: https://access.redhat.com/cspdownload/a33c7d593d220d62cdc90176a72468d8/644a1e98/JBEAP-7.2.0/jboss-eap-7.2.0.zip
      dest: /opt/jboss-eap-7.2.0.zip

   - name: Extract archive
     unarchive:
      dest: /opt/
      src: /opt/jboss-eap-7.2.0.zip
        #creates: /opt/jboss-eap-7.2
      copy: no

   - name: update domain host-master configuration file
     lineinfile:
      path: /opt/jboss-eap-7.2/domain/configuration/host-master.xml
      regexp: '^(.*)127\.0\.0\.1(.*)$'
      line: '\g<1>10.10.10.2\g<2>'
      backrefs: yes

   - name: update domain host-slave configuration file
     lineinfile:
      path: /opt/jboss-eap-7.2/domain/configuration/host-slave.xml
      regexp: '^(.*)host\="\$\{jboss\.domain\.master\.address}"(.*)$'
      line: '\g<1>host="10.10.10.2"\g<2>'
        #line: '\1host="10.10.10.2"\3'
      backrefs: yes

   - name: update domain host-slave configuration file==>replacing management ip<==
     lineinfile:
      path: /opt/jboss-eap-7.2/domain/configuration/host-slave.xml
      regexp: '^(.*)management\:127\.0\.0\.1(.*)$'
      line: '\g<1>management:10.10.10.3\g<2>'
      backrefs: yes

   - name: update domain host-slave configuration file==>replacing another ip<==
     lineinfile:
      path: /opt/jboss-eap-7.2/domain/configuration/host-slave.xml
      regexp: '^(.*)127\.0\.0\.1(.*)$'
      line: '\g<1>10.10.10.3\g<2>'
      backrefs: yes

   - name: create management user in jboss
     command: sh /opt/jboss-eap-7.2/bin/add-user.sh -u "{{ jbmgmtuser }}" -p "{{ jbmgmtpw }}"
     register: mgmtuser 

   - name: print the output of management user
     debug:
      msg: "{{ mgmtuser.stdout_lines }}"

