---
- name: Change the message
  hosts: all
  become: true
  tasks:
    - name: "Ensure the welcome login banner is configured properly"
      template:
       src: motd.j2
       dest: /etc/motd
       owner: root
       group: root
       mode: 0644

    - name: "Ensure local login warning banner is configured properly"
      template:
       src: issue.j2
       dest: /etc/issue
       owner: root
       group: root
       mode: 0644