---
- name: name service configuration
  hosts: all
  become: true
  tasks:
    - name: RHEL7.9 // Make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
      community.general.ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        state: present
        no_extra_spaces: yes
        section: main
        option: dns
        value: none
        owner: root
        group: root
        mode: 0644
        backup: yes
      tags: NetworkManager
      notify:
        - reload NetworkManager
      when: ansible_distribution =='RedHat'

    - name: RHEL7.9 // Deploy resolv.conf template
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
      tags: NetworkManager
      notify:
        - reload NetworkManager
      when: ansible_distribution =='RedHat'