---
- name: subscription-manager module
  hosts: all
  become: true
  vars:
    subscription_username: nandahein28
  tasks:
    - name: register with subscription-manager
      community.general.redhat_subscription:
        state: present
        username: "{{ subscription_username }}"
        password: "{{ subscription_password }}"
        auto_attach: true